.TH "BINMENU" "1" "November 2019" "Ben's Misc Scripts" "User Commands"
.SH NAME
binmenu \- custom dmenu app chooser script
.SH SYNOPSIS
.B binmenu
.RB [file]
.SH DESCRIPTION
binmenu is a simple dmenu script that allows for easy choosing of a program from
the given file. If no file is given, binmenu will use "$HOME/.config/binmenu"
.SH AUTHOR
Written by Ben O'Neill <ben@benoneill.xyz>.
.SH BUGS
If any bugs are found, email the author.
.SH COPYRIGHT
Copyright \(co 2019 Ben O'Neill <ben@benoneill.xyz>. License: GNU GPLv3+: GNU GPL
version 3 or later. <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR dmenu (1)
