.TH "BM" "1" "November 2019" "Ben's Misc Scripts" "User Commands"
.SH NAME
bm \- simple web bookmarking system
.SH SYNOPSIS
.B bm
.RB command
.RB [args...]
.SH DESCRIPTION
bm is a simple web bookmarking system packed into a small shell script.
It is intended to be used with a simple web browser, such as surf(1).
It uses dmenu(1) to display the menu.
.SH COMMANDS
.TP
.B add name url
Add a bookmark under
.B name
and
.B url
.TP
.B go name
Open bookmark
.B name
in
.B $BROWSER
which should be set to your preferred browser.
.TP
.B list
List all bookmarks
.TP
.B menu
List bookmarks in dmenu(1) and open selected bookmark in
.B $BROWSER
which should be set to your preferred browser.
.TP
.B remove name
Removes the bookmark defined by
.B name
.TP
.B rename oldname newname
Redefines the bookmarked defined by
.B oldname
to
.B newname
.TP
.B urls
lists all the bookmark URLs without the bookmark names.
.SH AUTHOR
Written by Ben O'Neill <ben@benoneill.xyz>.
.SH BUGS
If any bugs are found, email the author.
.SH COPYRIGHT
Copyright \(co 2019 Ben O'Neill <ben@benoneill.xyz>. License: GNU GPLv3+: GNU GPL
version 3 or later. <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR dmenu (1),
.BR surf (1)
