.TH "DMENUPASS" "1" "November 2019" "Ben's Misc Scripts" "User Commands"
.SH NAME
dmenupass \- dmenu password prompt
.SH SYNOPSIS
.B dmenupass
.SH DESCRIPTION
dmenupass allows the user to input a password through dmenu without showing the
text. It then prints the text to standard output.
.SH AUTHOR
Written by Ben O'Neill <ben@benoneill.xyz>.
.SH BUGS
If any bugs are found, email the author.
.SH COPYRIGHT
Copyright \(co 2019 Ben O'Neill <ben@benoneill.xyz>. License: GNU GPLv3+: GNU GPL
version 3 or later. <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR dmenu (1)
