.TH "DUCK" "1" "November 2019" "Ben's Misc Scripts" "User Commands"
.SH NAME
duck \- search DuckDuckGo in the command line or in dmenu
.SH SYNOPSIS
.B duck
.RB [query]
.SH DESCRIPTION
duck allows the user to search DuckDuckGo in the command line or using dmenu to
type their query. It then passes the result to surfraw.
.SH AUTHOR
Written by Ben O'Neill <ben@benoneill.xyz>.
.SH BUGS
If any bugs are found, email the author.
.SH COPYRIGHT
Copyright \(co 2019 Ben O'Neill <ben@benoneill.xyz>. License: GNU GPLv3+: GNU GPL
version 3 or later. <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR dmenu (1),
.BR surfraw (1)
