.TH "DWMBAR" "1" "November 2019" "Ben's Misc Scripts" "User Commands"
.SH NAME
dwmbar \- statusbar wrapper for dwm
.SH SYNOPSIS
.B dwmbar
.SH DESCRIPTION
dwmbar uses the program statusbar to display a self-updating status bar for
dwm through xsetroot.
.SH AUTHOR
Written by Ben O'Neill <ben@benoneill.xyz>.
.SH BUGS
If any bugs are found, email the author.
.SH COPYRIGHT
Copyright \(co 2019 Ben O'Neill <ben@benoneill.xyz>. License: GNU GPLv3+: GNU GPL
version 3 or later. <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR dwm (1),
.BR fifo (7),
.BR statusbar (1),
.BR xsetroot (1)
