.TH "MANMENU" "1" "November 2019" "Ben's Misc Scripts" "User Commands"
.SH NAME
manmenu \- choose a manual page to view
.SH SYNOPSIS
.B manmenu
.SH DESCRIPTION
manmenu provides an interface to choose a manual page to view in the default
terminal emulator (specified by $TERMINAL) using dmenu.
.SH AUTHOR
Written by Ben O'Neill <ben@benoneill.xyz>.
.SH BUGS
If any bugs are found, email the author.
.SH COPYRIGHT
Copyright \(co 2019 Ben O'Neill <ben@benoneill.xyz>. License: GNU GPLv3+: GNU GPL
version 3 or later. <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR dmenu (1),
.BR man (1)
