.TH "MDVIEW" "1" "November 2019" "Ben's Misc Scripts" "User Commands"
.SH NAME
mdview \- view Markdown files in Lynx
.SH SYNOPSIS
.B mdview
.RB file
.SH DESCRIPTION
mdview opens Markdown files in Lynx using smu to compile them. It does not save
the compiled HTML.
.SH AUTHOR
Written by Ben O'Neill <ben@benoneill.xyz>.
.SH BUGS
If any bugs are found, email the author.
.SH COPYRIGHT
Copyright \(co 2019 Ben O'Neill <ben@benoneill.xyz>. License: GNU GPLv3+: GNU GPL
version 3 or later. <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR lynx (1),
.BR smu (1)
