.TH "NOTIFYRAND" "1" "November 2019" "Ben's Misc Scripts" "User Commands"
.SH NAME
notifyrand \- show a random line from a file as notification
.SH SYNOPSIS
.B notifyrand
.RB title
.RB file
.SH DESCRIPTION
notifyrand sends a random line from a file to a notification. This is useful
if you want to show an inspiring quote or something along those lines.
.SH AUTHOR
Written by Ben O'Neill <ben@benoneill.xyz>.
.SH BUGS
If any bugs are found, email the author.
.SH COPYRIGHT
Copyright \(co 2019 Ben O'Neill <ben@benoneill.xyz>. License: GNU GPLv3+: GNU GPL
version 3 or later. <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR dunst (1),
.BR fortune (1)
