.TH "RSSADD" "1" "November 2019" "Ben's Misc Scripts" "User Commands"
.SH NAME
rssadd \- add RSS feed to Newsboat
.SH SYNOPSIS
.B rssadd
.RB url
.SH DESCRIPTION
rssadd adds a given RSS feed to the Newsboat urls file.
.SH AUTHOR
Written by Ben O'Neill <ben@benoneill.xyz>.
.SH BUGS
If any bugs are found, email the author.
.SH COPYRIGHT
Copyright \(co 2019 Ben O'Neill <ben@benoneill.xyz>. License: GNU GPLv3+: GNU GPL
version 3 or later. <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR newsboat (1)
