.TH "SONGMENU" "1" "November 2019" "Ben's Misc Scripts" "User Commands"
.SH NAME
songmenu \- mpd frontend in dmenu
.SH SYNOPSIS
.B songmenu
.SH DESCRIPTION
songmenu provides a dmenu interface for mpd, allowing one to search for tracks,
navigate their library, and access basic controls. It assumes that the audio
files are in the album directory which is in the artist directory.
.SH AUTHOR
Written by Ben O'Neill <ben@benoneill.xyz>.
.SH BUGS
If any bugs are found, email the author.
.SH COPYRIGHT
Copyright \(co 2019 Ben O'Neill <ben@benoneill.xyz>. License: GNU GPLv3+: GNU GPL
version 3 or later. <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR dmenu (1),
.BR mpc (1),
.BR mpd (1)
