.TH "SPELL" "1" "November 2019" "Ben's Misc Scripts" "User Commands"
.SH NAME
spell \- list misspelled words in a file
.SH SYNOPSIS
.B spell
.RB file
.SH DESCRIPTION
spell is a wrapper for the command aspell which lists the misspelled words in a
given file. This can then be used along with grep or sed to locate or replace
misspelled words for example.
.SH AUTHOR
Written by Ben O'Neill <ben@benoneill.xyz>.
.SH BUGS
If any bugs are found, email the author.
.SH COPYRIGHT
Copyright \(co 2019 Ben O'Neill <ben@benoneill.xyz>. License: GNU GPLv3+: GNU GPL
version 3 or later. <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR aspell (1),
.BR grep (1),
.BR sed (1)
