.TH "STACKOVERFLOW" "1" "November 2019" "Ben's Misc Scripts" "User Commands"
.SH NAME
stackoverflow \- search StackOverflow in the command line or in dmenu
.SH SYNOPSIS
.B stackoverflow
.RB [query]
.SH DESCRIPTION
stackoverflow allows the user to search StackOverflow in the command line or
using dmenu to type their query. It then opens the result in surfraw.
.SH AUTHOR
Written by Ben O'Neill <ben@benoneill.xyz>.
.SH BUGS
If any bugs are found, email the author.
.SH COPYRIGHT
Copyright \(co 2019 Ben O'Neill <ben@benoneill.xyz>. License: GNU GPLv3+: GNU GPL
version 3 or later. <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR dmenu (1),
.BR surfraw (1)
