.TH "WHATSONG" "1" "November 2019" "Ben's Misc Scripts" "User Commands"
.SH NAME
whatsong \- find out what song mpd is playing
.SH SYNOPSIS
.B whatsong
.SH DESCRIPTION
whatsong displays the currently playing song in mpd using the notify-send command in dunst.
.SH AUTHOR
Written by Ben O'Neill <ben@benoneill.xyz>.
.SH BUGS
If any bugs are found, email the author.
.SH COPYRIGHT
Copyright \(co 2019 Ben O'Neill <ben@benoneill.xyz>. License: GNU GPLv3+: GNU GPL
version 3 or later. <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR dunst (1),
.BR mpd (1)
