#!/bin/sh

# colors
alias ls="ls -h --group-directories-first --color=auto"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias less="less -R"

# shortcuts
alias pq="pacman -Qett | less"
alias yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'"
alias yta="yt -x -f bestaudio/best"
alias mutt="neomutt"
alias abook="abook -C $HOME/.config/abook/abookrc --datafile $HOME/.config/abook/addressbook"
