#!/bin/sh

cat <<EOF
[ \
    { \
        "application_id": xxx, \
        "state": null, \
        "details": "Arch Linux", \
        "large_image": { \
            "key": "large", \
            "text": null \
        }, \
        "small_image": null, \
        "start_timestamp": $(date -d "$(uptime -s)" +%s), \
        "end_timestamp": null, \
        "buttons": [ \
            { \
                "label": "?", \
                "url": "https://youtu.be/dQw4w9WgXcQ" \
            } \
        ] \
    } \
]
EOF
