#!/bin/sh

xset r rate 300 50 &
xrandr &
dunst &
unclutter &
slstatus &
pulseaudio -D &
xwallpaper --center ~/.local/share/wallpaper.png &
setxkbmap -option caps:escape
xset s off -dpms

eval $(/usr/bin/gnome-keyring-daemon --start --components=secrets)
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID

exec dwm
