#!/bin/sh

WALLPAPER=$(find ~/.local/share/wallpapers -type f | shuf -n 1)
xset r rate 300 50 &
xrandr &
dunst &
unclutter &
slstatus &
pulseaudio -D &
setxkbmap -option caps:escape
xset dpms 180 &
xss-lock -- slock &

xwallpaper --center $WALLPAPER &

exec dwm
