#!/bin/sh

xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5

bspc config top_padding 	     -15
bspc config bottom_padding 	     -15
bspc config left_padding 	     -15
bspc config right_padding 	     -15
bspc config border_width         2
bspc config window_gap           25
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
polybar default &
